---
# main tasks file for Ansible role pheus.netbox.nb_install

- name: Include PostgreSQL database installation and preparation tasks
  ansible.builtin.include_tasks:
    file: database.yml

- name: Include Redis caching server installation tasks
  ansible.builtin.include_tasks:
    file: cache.yml

...
