---
# tasks file for Nginx web server installation and configuration

- name: web | Ensure Nginx server package is installed
  become: true
  ansible.builtin.apt:
    pkg:
      - nginx
    state: present
    update_cache: true

- name: web | Create Nginx HTTP configuration file from template
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/netbox"
    group: "{{ nb_install_netbox_system_user }}"
    owner: "{{ nb_install_netbox_system_user }}"
    mode: "0644"
    backup: true
  notify: nginx-service-restart

- name: web | Ensure Nginx default configuration is disabled
  become: true
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: nginx-service-restart

- name: web | Enable NetBox Nginx configuration
  become: true
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/netbox"
    src: "/etc/nginx/sites-available/netbox"
    state: link
  notify: nginx-service-restart

...
