---
# defaults file for Ansible role pheus.netbox.nb_install

# NetBox configuration
######################

# NetBox allowed host list of fully-qualified domain names (FQDNs) for
# the NetBox server (wildcard '*' allows all host values)
nb_install_netbox_allowed_hosts:
  - "{{ nb_install_netbox_domain if not '_' else '*' }}"

# NetBox web service fully-qualified domain name (FQDN)
# (e.g. netbox.example.org)
nb_install_netbox_domain: "_"

# NetBox installation path (and home of nb_install_netbox_system_user)
nb_install_netbox_install_path: "/opt/netbox"

# NetBox randomly-generated key employed as a salt for hashing and
# related cryptographic functions
# (recommended to be at least 50 characters)
nb_install_netbox_secret_key: "{{ lookup('ansible.builtin.password',
  '/dev/null', chars=['ascii_letters', 'digits', '!@#$%^&*(-_=+)'],
  length=50, seed=inventory_hostname) }}"

# NetBox (Django) superuser creation enabled
nb_install_netbox_superuser_creation_enabled: true

# NetBox superuser username
nb_install_netbox_superuser_username: admin

# NetBox superuser user email address
nb_install_netbox_superuser_email: "admin@example.org"

# NetBox superuser password
# nb_install_netbox_superuser_password: "ADD A SUPERUSER PASSWORD"

# NetBox system user
nb_install_netbox_system_user: netbox

# NetBox time zone
nb_install_netbox_time_zone: UTC

# NetBox installation version (e.g. v3.7.5, default: master branch)
nb_install_netbox_version: latest


# NetBox database configuration
###############################

# Database name
nb_install_database_name: netbox

# Database user name
nb_install_database_user_name: netbox

# Database user password
nb_install_database_user_password: "{{ lookup('ansible.builtin.password',
  '/dev/null', length=32, seed=inventory_hostname) }}"


# NetBox housekeeping configuration
###################################

# Housekeeping cron job file name (in /etc/cron.daily/)
nb_install_netbox_housekeeping_cron_job_file: netbox-housekeeping.sh


# NetBox web server configuration
#################################

# Web server fully-qualified domain name (FQDN)
nb_install_web_server_domain: "{{ nb_install_netbox_domain }}"

# Web server TLS certificate path
nb_install_web_server_tls_cert_path: "/etc/ssl/certs/netbox.crt"

# Web server TLS certificate key path:
nb_install_web_server_tls_cert_key_path: "/etc/ssl/private/netbox.key"

...
