---
# defaults file for Ansible role pheus.netbox.nb_install

# NetBox configuration
######################

# NetBox allowed host list of fully-qualified domain names (FQDNs) for
# the NetBox server (wildcard '*' allows all host values)
nb_install_netbox_allowed_hosts:
  - "*"

# NetBox installation path (and home of nb_install_netbox_system_user)
nb_install_netbox_install_path: "/opt/netbox"

# NetBox randomly-generated key employed as a salt for hashing and
# related cryptographic functions
# (recommended to be at least 50 characters)
nb_install_netbox_secret_key: "{{ lookup('ansible.builtin.password',
  '/dev/null', chars=['ascii_letters', 'digits', '!@#$%^&*(-_=+)'],
  length=50, seed=inventory_hostname) }}"

# NetBox system user
nb_install_netbox_system_user: netbox

# NetBox time zone
nb_install_netbox_time_zone: UTC

# NetBox installation version
nb_install_netbox_version: latest


# NetBox database configuration
###############################

# Database name
nb_install_database_name: netbox

# Database user name
nb_install_database_user_name: netbox

# Database user password
nb_install_database_user_password: "{{ lookup('ansible.builtin.password',
  '/dev/null', length=32, seed=inventory_hostname) }}"

...
