---
# handlers file for Ansible role pheus.netbox.nb_install

- name: Execute the NetBox upgrade script
  become: true
  ansible.builtin.command:
    cmd: "{{ nb_install_netbox_install_path }}/upgrade.sh"
    chdir: "{{ nb_install_netbox_install_path }}"
  changed_when:
    - "'No migrations to apply.' not in __nb_install_upgrade_result.stdout"
  failed_when:
    - "__nb_install_upgrade_result.rc != 0"
    - "'Upgrade complete!' not in __nb_install_upgrade_result.stdout"
  listen: netbox-upgrade-script
  register: __nb_install_upgrade_result

...
